neo4j-graphacademy/courses

asciidoc/emails/user-completed-course.adoc
asciidoc/emails/user-enrolled.adoc

Add NODES 2022 text to emails

---

asciidoc/courses/graph-data-science-fundamentals/modules/1-graph-algorithms/lessons/9-similarity/lesson.adoc

Fixed, typos, improper case and grammar issues

Update to Similarity docs

---

asciidoc/courses/app-java/modules/0-setup/lessons/2-sandbox/lesson.adoc
asciidoc/courses/app-java/modules/1-driver/lessons/1-about/questions/2-package-name.adoc
asciidoc/courses/app-java/modules/1-driver/lessons/3-connecting/questions/1-test-number.adoc
asciidoc/courses/app-java/modules/2-interacting/lessons/1-transactions/lesson.adoc
asciidoc/courses/app-java/modules/2-interacting/lessons/1-transactions/questions/1-valid-methods.adoc
asciidoc/courses/app-java/modules/2-interacting/lessons/1-transactions/questions/2-read-transaction.adoc
asciidoc/courses/app-java/modules/2-interacting/lessons/1-transactions/questions/3-write-transaction.adoc
asciidoc/courses/app-java/modules/2-interacting/lessons/10-user-favorites/questions/verify.adoc
asciidoc/courses/app-java/modules/2-interacting/lessons/10-user-favorites/solution.cypher
asciidoc/courses/app-java/modules/2-interacting/lessons/11-favorite-flag/questions/verify.adoc
asciidoc/courses/app-java/modules/2-interacting/lessons/11-favorite-flag/solution.cypher
asciidoc/courses/app-java/modules/2-interacting/lessons/2-results/questions/1-method.adoc
asciidoc/courses/app-java/modules/2-interacting/lessons/3-type-system/questions/1-node-property.adoc
asciidoc/courses/app-java/modules/2-interacting/lessons/3-type-system/questions/2-temporal.adoc
asciidoc/courses/app-java/modules/2-interacting/lessons/4-home-page/lesson.adoc
asciidoc/courses/app-java/modules/2-interacting/lessons/4-home-page/questions/verify.adoc
asciidoc/courses/app-java/modules/2-interacting/lessons/5-registering/lesson.adoc
asciidoc/courses/app-java/modules/2-interacting/lessons/5-registering/questions/verify.adoc
asciidoc/courses/app-java/modules/2-interacting/lessons/5-registering/solution.cypher
asciidoc/courses/app-java/modules/2-interacting/lessons/6-driver-errors/questions/1-error-code.adoc
asciidoc/courses/app-java/modules/2-interacting/lessons/6-driver-errors/questions/2-error-details.adoc
asciidoc/courses/app-java/modules/2-interacting/lessons/7-unique-emails/questions/verify.adoc
asciidoc/courses/app-java/modules/2-interacting/lessons/7-unique-emails/solution.cypher
asciidoc/courses/app-java/modules/2-interacting/lessons/8-authenticating/questions/verify.adoc
asciidoc/courses/app-java/modules/2-interacting/lessons/8-authenticating/solution.cypher
asciidoc/courses/app-java/modules/2-interacting/lessons/9-ratings/questions/verify.adoc
asciidoc/courses/app-java/modules/2-interacting/lessons/9-ratings/solution.cypher
asciidoc/courses/app-java/modules/3-backlog/lessons/3-movie-lists/lesson.adoc

Update app-java to 5.1 drivers

---

asciidoc/courses/gds-product-introduction/modules/2-graph-management/lessons/2-native-projections/lesson.adoc
asciidoc/courses/graph-data-science-fundamentals/modules/1-graph-algorithms/lessons/4-path-finding/lesson.adoc
asciidoc/courses/graph-data-science-fundamentals/modules/1-graph-algorithms/lessons/8-node-embeddings/lesson.adoc
asciidoc/courses/graph-data-science-fundamentals/modules/2-machine-learning-procedures/lessons/4-link-prediction/lesson.adoc

This has nothing to do with version compatibility

Small Changes for Course Feedback and Links

---

asciidoc/courses/modeling-fundamentals/modules/1-getting-started/lessons/1-what-is-modeling/lesson.adoc
asciidoc/courses/modeling-fundamentals/modules/7-using-specific-relationships/lessons/1-specific-relationships/lesson.adoc

A couple of minor fixes for the modelling-fundamentals course. A typo + a script which was inconsistent across a couple of lessons and had only been updated in 1 place.

Data modelling fixes

---

asciidoc/courses/gds-community-detection/modules/2-preprocess/lessons/3-c-categorical/reset.cypher
asciidoc/courses/gds-community-detection/modules/2-preprocess/lessons/4-dimensionality/reset.cypher

reset.cypher in GDS Community Detection deletes all Person nodes when it should load them

fix reset cypher

---

asciidoc/courses/llm-fundamentals/modules/3-intro-to-langchain/lessons/3-chat-models/questions/1-message-types.adoc

Fixing the grammar for this question

Fix question grammar

---

asciidoc/courses/administration-cluster/course.adoc
asciidoc/courses/administration-linux/course.adoc
asciidoc/courses/administration-production/course.adoc
asciidoc/courses/administration-windows/course.adoc
asciidoc/courses/administrator-fundamentals/course.adoc
asciidoc/courses/administrator-graph-platform/course.adoc
asciidoc/courses/administrator-single/course.adoc
asciidoc/courses/applied-data-science/course.adoc
asciidoc/courses/aura-drivers/course.adoc
asciidoc/courses/aura-fundamentals/course.adoc
asciidoc/courses/aura-import/course.adoc
asciidoc/courses/cypher-import/course.adoc
asciidoc/courses/cypher-temporal-spatial/course.adoc
asciidoc/courses/data-scientist-import/course.adoc
asciidoc/courses/data-scientist-python/course.adoc
asciidoc/courses/gds-community-detection/course.adoc
asciidoc/courses/graphql-ogm/course.adoc

This PR disables:
- courses which wont be progressing in the short to medium term
- GDS community detection which has issues which will take significant effort to resolve

Disable courses

---

asciidoc/courses/importing-fundamentals/modules/2-data-importer/lessons/1-importing-nodes/lesson.adoc

Minor fixes

---

asciidoc/courses/cypher-fundamentals/modules/1-reading/lessons/3-relationships/questions/2-directors.adoc

I think there might be more places that we could add this, to make it super obvious that the question requires ticking multiple answers. Please think of this commit as the start of a discussion - if agreed then I'm happy to go through and find others and update the PR.

Make multiple choice more obvious

---

.vscode/asciidoc.code-snippets
asciidoc/courses/app-dotnet/ad.adoc
asciidoc/courses/app-dotnet/promo.adoc
asciidoc/courses/app-go/ad.adoc
asciidoc/courses/app-go/promo.adoc
asciidoc/courses/app-java/ad.adoc
asciidoc/courses/app-java/promo.adoc
asciidoc/courses/app-nodejs/course.adoc
asciidoc/courses/app-python/ad.adoc
asciidoc/courses/app-python/promo.adoc
asciidoc/courses/app-typescript/ad.adoc
asciidoc/courses/app-typescript/course.adoc
asciidoc/courses/app-typescript/promo.adoc

* `ad.adoc` should be included at the top of a page to set the attributes for a file
*  `promo.adoc` should be included at the bottom of the page to provide the user with next steps
Files added to app-* courses only, more to follow

Add promo and ad files for Docs

---

asciidoc/courses/cypher-fundamentals/modules/2-writing/lessons/5-updating-properties/lesson.adoc

A couple of proposed minor edits.

Change cypher to match description

---

asciidoc/courses/llm-vectors-unstructured/modules/2-vector-indexes/lessons/2-load-embeddings/lesson.adoc

changed from 
https://raw.githubusercontent.com/neo4j-graphacademy/llm-vectors-unstructured/main/solutions/quora_embeddings.py 
to  this
https://raw.githubusercontent.com/neo4j-graphacademy/llm-vectors-unstructured/main/llm-vectors-unstructured/solutions/quora_embeddings.py

Update lesson.adoc (Link  not working)

---

asciidoc/courses/gds-product-introduction/modules/2-graph-management/lessons/4-cypher-projection/lesson.adoc
asciidoc/courses/gds-product-introduction/modules/2-graph-management/lessons/4-cypher-projection/reset.cypher

Hey!
Thanks for the course. Found a small typo in the query for the `Cypher Projections` lesson.
Here is the fix

Fix the query for the Cypher Projections lesson

---

asciidoc/courses/genai-workshop/modules/1-knowledge-graphs-vectors/lessons/4-embeddings/lesson.adoc
asciidoc/courses/genai-workshop/modules/2-llm-rag-python-langchain/lessons/5-chat-models/lesson.adoc
asciidoc/courses/genai-workshop/modules/2-llm-rag-python-langchain/lessons/6-agents/lesson.adoc

1 fix and a couple of minor updates I noted when going through the genai-workshop

genai-workshop - minor fix and improvements

---

asciidoc/courses/genai-workshop/modules/1-knowledge-graphs-vectors/lessons/1-getting-started/lesson.adoc
asciidoc/courses/genai-workshop/modules/1-knowledge-graphs-vectors/lessons/4-embeddings/lesson.adoc
asciidoc/courses/genai-workshop/modules/1-knowledge-graphs-vectors/lessons/7-import-unstructured-data/lesson.adoc
asciidoc/courses/genai-workshop/modules/1-knowledge-graphs-vectors/lessons/9-build-graph/lesson.adoc
asciidoc/courses/genai-workshop/modules/2-llm-rag-python-langchain/lessons/3-python-langchain/lesson.adoc
asciidoc/courses/genai-workshop/modules/2-llm-rag-python-langchain/lessons/5-chat-models/lesson.adoc
asciidoc/courses/genai-workshop/modules/2-llm-rag-python-langchain/lessons/6-agents/lesson.adoc
asciidoc/courses/genai-workshop/modules/2-llm-rag-python-langchain/lessons/7-retrievers/lesson.adoc
asciidoc/courses/genai-workshop/modules/2-llm-rag-python-langchain/lessons/8-create-a-retriever/lesson.adoc
asciidoc/courses/genai-workshop/modules/2-llm-rag-python-langchain/lessons/9-cypher-generation/lesson.adoc

This change is dependent on https://github.com/neo4j-graphacademy/genai-workshop/pull/3

genai-workshop updates

---

asciidoc/courses/cypher-intermediate-queries/modules/5-pipelining-queries/lessons/11-c2-unwind/lesson.adoc
asciidoc/courses/cypher-intermediate-queries/modules/5-pipelining-queries/lessons/11-c2-unwind/questions/q2.adoc

Changed country to Switzerland to resolve #265

Resolve #265

---

asciidoc/courses/llm-vectors-unstructured/modules/3-unstructured-data/lessons/0-setup/lesson.adoc

Changes llm-vectors-unstructured to use github codespaces
Dependent on https://github.com/neo4j-graphacademy/llm-vectors-unstructured/pull/9

Move llm-vectors-unstructured to github codespaces

---

asciidoc/courses/graph-data-science-fundamentals/modules/1-graph-algorithms/lessons/3-c-centrality-and-importance/questions/verify.adoc
asciidoc/courses/graph-data-science-fundamentals/modules/1-graph-algorithms/lessons/3-c-centrality-and-importance/sandbox.cypher
asciidoc/courses/graph-data-science-fundamentals/modules/1-graph-algorithms/lessons/3-c-centrality-and-importance/solution.cypher

Learners are getting confused, running both queries at the same time and not seeing the result as browser is summarising the calls.

Make GDS challenge clearer

---

asciidoc/courses/llm-chatbot-python/modules/1-project-setup/lessons/2-setup/lesson.adoc
asciidoc/courses/llm-chatbot-python/modules/1-project-setup/module.adoc
asciidoc/courses/llm-vectors-unstructured/modules/3-unstructured-data/lessons/0-setup/lesson.adoc
asciidoc/shared/courses/codespace/get-started.adoc

Dependent on https://github.com/neo4j-graphacademy/llm-chatbot-python/pull/23

Migrate to llm-chatbot-python to codespaces

---

asciidoc/courses/app-typescript/modules/1-driver/lessons/1-installation/lesson.adoc
asciidoc/courses/app-typescript/modules/1-driver/lessons/2-c-create-driver/lesson.adoc
asciidoc/courses/app-typescript/modules/1-driver/lessons/2-c-create-driver/questions/1-director.adoc
asciidoc/courses/app-typescript/modules/1-driver/lessons/5-c-writing-data/lesson.adoc
asciidoc/courses/app-typescript/modules/1-driver/lessons/5-c-writing-data/questions/verify.adoc

I also scaffolded the challenges with code snippets based on feedback for the challenges
Dependent on PR - https://github.com/neo4j-graphacademy/app-typescript/pull/6

Migrate app-typescript to codespace

---

asciidoc/courses/genai-workshop-graphrag/modules/1-knowledge-graphs-vectors/lessons/1-getting-started/lesson.adoc

https://github.com/neo4j-graphacademy/genai-workshop-graphrag/pull/9

Migrate genai-workshop-graphrag to codespace

---

asciidoc/courses/llm-knowledge-graph-construction/modules/3-python-create-graph/lessons/1-setup/lesson.adoc

Dependent on https://github.com/neo4j-graphacademy/llm-knowledge-graph-construction/pull/11

Migrate llm-knowledge-graph-construction to codespace

---

asciidoc/courses/graphql-basics/modules/1-introduction/lessons/2-neo4j-graphql/lesson.adoc
asciidoc/emails/user-completed-course.adoc
asciidoc/emails/user-created-team.adoc
asciidoc/emails/user-enrolled.adoc
asciidoc/emails/user-enrolment-reminder.adoc
asciidoc/shared/nodes2025.adoc

Adds NODES 2025 links to emails.
Do not merge until Wednesday 2 April at 13:00 BST.

Nodes 2025 CFP

---

asciidoc/courses/app-java/modules/1-getting-started/lessons/1-setup/lesson.adoc
asciidoc/courses/drivers-java/course.adoc
asciidoc/courses/drivers-java/modules/2-handling-results/lessons/1-type-system/lesson.adoc
asciidoc/courses/drivers-java/modules/2-handling-results/lessons/4c-working-with-dates-and-times/questions/1-datetime-creation.adoc
asciidoc/courses/drivers-java/modules/3-in-production/lessons/4c-handling-errors/questions/1-constraint-error.adoc
asciidoc/courses/workshop-fundamentals/course.adoc

Minor updates based on feedback

Fixes to drivers-java & workshop-fundamentals

---

asciidoc/courses/drivers-java/modules/1-driver/lessons/0-setup/lesson.adoc
asciidoc/courses/drivers-java/modules/1-driver/lessons/1-driver-lifecycle/lesson.adoc
asciidoc/courses/drivers-java/modules/1-driver/lessons/3-execute-query/lesson.adoc
asciidoc/courses/drivers-java/modules/1-driver/lessons/4c-your-first-query/questions/1-execute-query.adoc
asciidoc/courses/drivers-java/modules/1-driver/lessons/4c-your-first-query/questions/2-access-results.adoc
asciidoc/courses/drivers-java/modules/3-in-production/lessons/1-transaction-management/lesson.adoc

* Update 1-driver/2-execute-query lesson for method name in lesson summary

Updates for typos and things missed

---

asciidoc/courses/genai-mcp-neo4j-tools/course.adoc
asciidoc/courses/genai-mcp-neo4j-tools/modules/1-what-is-mcp/lessons/1-getting-started/lesson.adoc
asciidoc/courses/genai-mcp-neo4j-tools/modules/1-what-is-mcp/lessons/4c-install-mcp-neo4j-cypher/lesson.adoc
asciidoc/courses/genai-mcp-neo4j-tools/modules/1-what-is-mcp/lessons/4c-install-mcp-neo4j-cypher/questions/1-tools-available.adoc
asciidoc/courses/genai-mcp-neo4j-tools/modules/1-what-is-mcp/module.adoc
asciidoc/courses/genai-mcp-neo4j-tools/modules/2-using-neo4j-mcp-tools/lessons/1-mcp-neo4j-cypher/lesson.adoc
asciidoc/courses/genai-mcp-neo4j-tools/modules/2-using-neo4j-mcp-tools/lessons/3c-generating-cypher-statements/questions/1-highest-rated-movie.adoc

Dependent on https://github.com/neo4j-graphacademy/genai-mcp-neo4j-tools/pull/1

genai-mcp-neo4j-tool - updates post testing

---

asciidoc/courses/genai-fundamentals/modules/2-rag/lessons/3-vector-index/lesson.adoc
asciidoc/courses/genai-fundamentals/modules/2-rag/lessons/4-graphrag/reset.cypher
asciidoc/courses/genai-fundamentals/modules/4-integrating-neo4j/lessons/3-rag/reset.cypher
asciidoc/courses/genai-fundamentals/modules/4-integrating-neo4j/lessons/4-vector-graph/reset.cypher
asciidoc/courses/genai-integration-langchain/modules/2-vectors/lessons/1-vector-search/lesson.adoc
asciidoc/courses/genai-integration-langchain/modules/2-vectors/lessons/2-vector-retriever/reset.cypher
asciidoc/courses/genai-integration-langchain/modules/2-vectors/lessons/3-graph-retrieval/reset.cypher

Added additional information about how plot embeddings are loaded and how the vector index is created.
Added reset scripts to additional lessons that rely on the the vector index. This is to cater for people returning to a course after the sandbox has expired.
https://community.neo4j.com/t/graph-academy-sandbox-refusing-to-connect/72609/20?u=martin.ohanlon

Added additional reset scripts and instructions

---

.cursor/review-lesson-content.mdc
asciidoc/courses/genai-mcp-neo4j-tools/llms.txt
asciidoc/courses/modeling-fundamentals/course.adoc
asciidoc/courses/modeling-fundamentals/modules/2-defining-nodes/lessons/2-c-creating-initial-nodes/lesson.adoc
asciidoc/courses/modeling-fundamentals/modules/2-defining-nodes/lessons/3-c-defining-nodes/lesson.adoc
asciidoc/courses/modeling-fundamentals/shared/using-aura-instance-provider.adoc

To merge and release on Monday 8 September.

Use aura instance provider for modeling-fundamentals

---

asciidoc/courses/neo4j-fundamentals/modules/2-querying-graphs/lessons/1-reading-data/lesson.adoc
asciidoc/courses/workshop-fundamentals/modules/1-neo4j-fundamentals/lessons/3-reading-data/lesson.adoc

Minor fixes - merge at the next release
